apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-fastapi-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-fastapi-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 5  # Scale up when average requests per second exceeds 10
